server:
  port: 9999	
spring:
  application:
    name: cs-edgeservice
  cloud:
    gateway:
      routes:
      - id: query-service-get-all
        uri: lb://cs-query
        predicates:
        - Path=/menu
        - Method=GET
      - id: command-service-create
        uri: lb://cs-commands
        predicates:
        - Path=/menu
        - Method=POST
      - id: command-service-update
        uri: lb://cs-commands
        predicates:
        - Path=/menu/{id}
        - Method=PUT
      - id: command-service-delete
        uri: lb://cs-commands
        predicates:
        - Path=/menu/{id}
        - Method=DELETE
      discovery:
        locator:
          enabled: true
     