server:
  port: 9999	
spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: localhost:9411
  application:
    name: cs-edgeservice
  cloud:
    gateway:
      routes:
      - id: query-service-get-all
        uri: lb://cs-query
        predicates:
        - Path=/menu
        - Method=GET
      - id: command-service-create
        uri: lb://cs-commands
        predicates:
        - Path=/menu
        - Method=POST
      - id: command-service-update
        uri: lb://cs-commands
        predicates:
        - Path=/menu/{id}
        - Method=PUT
      - id: command-service-delete
        uri: lb://cs-commands
        predicates:
        - Path=/menu/{id}
        - Method=DELETE
      discovery:
        locator:
          enabled: true
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    service:
      name: ${spring.application.name}  
  sleuth:
    sampler:
      probability: 1  