server:
  port: 8010
spring:
  application:
    name: Menu-UI
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html  
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?autoReconnect=true&useSSL=false
    username: user_1
    password: test
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO  

menu:
  ribbon:
    listOfServers: localhost:9999